### ISSUE TITLE
Restrict django-test-pipeline to specific directories only

### ISSUE THREAD

**Issue by sadikkuzu** [SWE574-Fall2023-Group1/SWE574-Fall2023-G1#228]
Use such `paths` configuration:

```yaml
name: Django test pipeline
on:
  pull_request:
    paths:
      - 'backend/backend/**'
      - 'backend/user/**'
      - 'backend/manage.py'
      - 'backend/requirements.txt'
```
